### ISSUE TITLE
GifTextureView crash (IllegalStateException: Poll failed)

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable-sample#1]
Repro steps:
1) Open sample app;
2) swipe  --> from SourcesFragment to TextViewFragment;
3) swipe back <-- to SourcesFragment;
4) Swipe left <-- again.

Stack trace:

```
03-28 10:24:44.806    1246-1441/pl.droidsonroids.gif.sample E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-91
    java.lang.IllegalStateException: Poll failed
            at pl.droidsonroids.gif.GifInfoHandle.bindSurface(Native Method)
            at pl.droidsonroids.gif.GifInfoHandle.bindSurface(GifInfoHandle.java:118)
            at pl.droidsonroids.gif.GifTextureView$RenderThread.run(GifTextureView.java:191)
03-28 10:24:44.834      385-397/system_process E/Sensors﹕ Select fail, disconnect all clients (errno=4)
03-28 10:24:45.418      385-444/system_process E/ActivityManager﹕ ANR in pl.droidsonroids.gif.sample (pl.droidsonroids.gif.sample/.MainActivity)
    Reason: keyDispatchingTimedOut
    Load: 0.02 / 0.04 / 0.02
    CPU usage from 39803ms to 3863ms ago with 99% awake:
    4% 1246/pl.droidsonroids.gif.sample: 3.3% user + 0.7% kernel / faults: 1136 minor
    1.2% 113/local_opengl: 0% user + 1.2% kernel
    0.8% 404/surfaceflinger: 0.3% user + 0.4% kernel
    0.5% 385/system_server: 0.3% user + 0.2% kernel / faults: 84 minor
    0.4% 60/adbd: 0% user + 0.4% kernel / faults: 1849 minor
    0% 111/vinput: 0% user + 0% kernel
    0% 383/logcat: 0% user + 0% kernel
    0% 588/com.android.phone: 0% user + 0% kernel / faults: 74 minor
    6.8% TOTAL: 3.5% user + 2.7% kernel + 0.5% softirq
    CPU usage from 117ms to 618ms later:
    6% 385/system_server: 4% user + 2% kernel / faults: 930 minor
    2% 400/WindowManager: 0% user + 2% kernel
    2% 401/ActivityManager: 2% user + 0% kernel
    2% 685/Binder_7: 2% user + 0% kernel
    4% 404/surfaceflinger: 0% user + 4% kernel
    2% 406/SurfaceFlinger: 0% user + 2% kernel
    2% 416/VSyncThread: 0% user + 2% kernel
    2% 420/Binder_1: 2% user + 0% kernel
    8.5% TOTAL: 4.2% user + 2.1% kernel + 2.1% softirq
03-28 10:24:47.138      385-444/system_process E/InputDispatcher﹕ channel '53a8b2dc pl.droidsonroids.gif.sample/pl.droidsonroids.gif.sample.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by koral--** [comment]
I could not reproduce it using current version, however now `errno` is added to such kind error messages so it will be easier to debug if it occurs in the future.
If app was force closed due to ANR then `poll()` might fail with errno=`EINTR` but again I was unable to reproduce ANR. 
I guess that it might be caused by the fact that in `SourcesFragment` many GIFs are loaded in UI thread and on some (especially slow/busy) devices it may take time long enough for ANR.
I'll move loading in sample to background thread.

**Comment by PaulProject** [comment]
Hi Karol,

I can reproduce this error on the emulator Genimotion v 2.5.0 (Google Nexus 5 - 5.1.0 - API 22 - 1080x1920) when try play gif downloaded from url

**Comment by koral--** [comment]
Tracked as https://github.com/koral--/android-gif-drawable/issues/240#issuecomment-169831018 in library project.
